name: baseline-profiles

on:
  push:
    branches:
      - feature**

jobs:

  generate-baseline-profiles:

    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant Permissions to gradlew
        run: chmod +x gradlew

      - name: Clean Managed Devices
        run: ./gradlew cleanManagedDevices --unused-only

      - name: Generate Baseline Profile
        run: ./gradlew :benchmark:pixel6Api31BenchmarkAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile -Dorg.gradle.workers.max=4

      - name: Move & Rename Baseline Profiles
        run: |
          mv -f benchmark/build/outputs/managed_device_android_test_additional_output/pixel6Api31/BaselineProfileGenerator_startup-baseline-prof.txt app/src/main/baseline-prof.txt

      # Commits the generated Baseline Profile to your origin/remote
      - name: Commit Baseline Profiles
        run: |
          git config --global user.name 'masato1230'
          git config --global user.email ''
          git add app/src/main/baseline-prof.txt
          git commit -m "Generate baseline profiles"
          git push